#!/bin/bash
tred=$(tput setaf 1)
treset=$(tput sgr0)
latex_dir=$(dirname $(kpsewhich article.cls))

function trycopy() {
	file=$1
	dir="$2"

	if [ -d "$dir" ] ; then
		cp -vf "$file" "$dir"
	fi
}

echo "Creating completion files..."
cwlpaths="~/.config/texstudio/ ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/cwl/ ~/.config/sublime-text-3/Packages/User/cwl/"

for sty in $(ls *.sty) ; do
	cwl="${sty/%.sty/.cwl}"
	echo "$sty -> $cwl"
	python cwlcreator.py $sty $cwl

	for path in $cwlpaths ; do
		trycopy $cwl $path
	done
done

echo "Copying packages..."
if ! cp -v *.code.tex *.sty $latex_dir ; then
	echo "${tred}Error copying packages! Did you run with sudo?${treset}"
	exit
else
	echo "Packages copied."
fi

echo "Copying classes..."

if ! cp -v *.cls $latex_dir ; then
	echo "${tred}Error copying classes! Did you run with sudo?${treset}"
	exit
else
	echo "Classes copied"
fi

echo "Copying images..."

if ! cp -v *.eps $latex_dir ; then
	echo "${tred}Error copying images! Did you run with sudo?${treset}"
	exit
else
	echo "Images copied"
fi


echo "Updating package cache..."

if ! texhash ; then
	echo "${tred}Couldn't update cache${treset}"
else
	echo "Package cache updated."
fi

echo "Finished"
